---
title: "Justice40+: Adding Racial Demographics and Census Tract Shape Files to the J40 ToolR."
author: "Ben Burnley"
date: "7/25/2022"
output: html_document
---

```{r}
# install packages 
install.packages("tidyverse")
install.packages("tidycensus")
install.packages("tigris")
install.packages("sf")
install.packages("yardstick")
install.packages("cvms")
install.packages("naniar")
install.packages("patchwork")
install.packages("heatmetrics")


# load packages
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
library(yardstick)
library(cvms)
library(naniar)
library(patchwork)

# options 
options(tigris_use_cache = TRUE)
```

```{r}
#load data 
Justice40Tool_transformed <- read_csv("~/Desktop/Projects/Justice40Tool_transformed.csv")
data <- as.tibble(Justice40Tool_transformed)
head(data)
FEMA_national_risk_index <-read_csv("~/Desktop/Projects/fema_tract_level.csv")
fema_risk <- as.tibble(FEMA_national_risk_index)
```

```{r}
# pulling census data from U.S. Census Bureau API via tidycensus

#setting census API key. This is my personal key from the census bureau. 
credential <- Sys.getenv("7cbd3daa5e7971ae8c363192b9e829a4d16a5567")

# selecting the race variables we are interested in from the 2020 ACS. This is currently the most up to date estimate
race_vars <- c(
  White = "B03002_003",
  Black = "B03002_004",
  Native = "B03002_005",
  Asian = "B03002_006",
  HIPI = "B03002_007",
  Hispanic = "B03002_012"
)
#getting all fips codes 
fips_codes_simple = fips_codes%>%
  select(state_code,state_name) %>%
  distinct()

#state_codes = fips_codes_simple %>%
  #mutate(state_code_numeric = as.numeric(state_code)) %>% 
  #select(state_code_numeric)

states =  c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56,72)


# pulling race variables from ACS by census tract
tract_race = get_acs(
    geography = "tract",
    state = states,
    variables = race_vars,
    summary_var = "B03002_001",
    year = 2019, 
    output = "wide",
    key = credential,
    geometry = TRUE    #includes the shape file for each tract
    ) %>%
  separate(NAME, 
           into = c("tract", "county", "state"),   #separates the NAME column into constituent parts
           sep = ", ")
head(tract_race)
```

```{r}
# merging process
#j40_race = data %>%
    #left_join(tract_race, by = c("geoid10_tract" = "GEOID"))
j40_race = tract_race %>%
  left_join(data, by = c("GEOID" = "geoid10_tract"))
head(j40_race)
#Head of J40 Tool with race variables added for each tract
```

```{r}
# create percentage variables 
j40_race = j40_race %>%
mutate(white_pct = WhiteE/summary_est, 
       black_pct = BlackE/summary_est,
       native_pct = NativeE/summary_est,
       asian_pct = AsianE/summary_est,
       hipi_pct = HIPIE/summary_est,
       hispanic_pct = HispanicE/summary_est,
       majority_minority = if_else(white_pct < .50, 1, 0),
       non_white_pct = (summary_est - WhiteE)/summary_est)
```

```{r}
#simple table of Justice40 disadvantaged communities vs. majority-minority communites
j40_disadvantaged = j40_race$definition_m_pctl
maj_min_communities = j40_race$majority_minority
outcomes = table(j40_disadvantaged, maj_min_communities)
outcomes
```

```{r}
#visualization of the matrix of outcomes
outcomes_m = conf_mat(outcomes)
autoplot(outcomes_m)+
  labs(x = "Majority-Minority Community",
       y = "Justice 40 Disadvantaged",
       title = "Race and Justice40 Disadvantaged Status")
```

```{r}
# another visualization option 
outcomes_tibble = as_tibble(outcomes)
outcomes_tibble
plot_confusion_matrix(outcomes_tibble, target_col = "j40_disadvantaged", prediction_col = "maj_min_communities", counts_col = "n", add_counts = F)+
  labs(x = "Justice40 Disadvantaged Tracts",
       y = "Majority-Minority Tracts",
       title = "Race and Justice40 Disadvantaged Status")+
  scale_x_discrete(labels = c("No", "Yes"), position = "top")+
  scale_y_discrete(labels = c("No", "Yes"))
```

```{r}
j40_select = j40_race %>%
  select(definition_m_pctl,non_white_pct, summary_est)%>%
  filter(!is.na(non_white_pct)) %>%
  mutate(percentile = if_else(non_white_pct >= 0.00 & non_white_pct< 0.05 , "0%",
                              if_else(non_white_pct >= 0.05 & non_white_pct < 0.10, "5%",
                              if_else(non_white_pct >= 0.10 & non_white_pct < 0.15, "10%",
                              if_else(non_white_pct >= 0.15 & non_white_pct < 0.20, "15%",
                              if_else(non_white_pct >= 0.20 & non_white_pct < 0.25, "20%",
                              if_else(non_white_pct >= 0.25 & non_white_pct < 0.30, "25%",
                              if_else(non_white_pct >= 0.30 & non_white_pct < 0.35, "30%",
                              if_else(non_white_pct >= 0.35 & non_white_pct < 0.40, "35%",
                              if_else(non_white_pct >= 0.40 & non_white_pct < 0.45, "40%",
                              if_else(non_white_pct >= 0.45 & non_white_pct < 0.50, "45%",
                              if_else(non_white_pct >= 0.50 & non_white_pct < 0.55, "50%",
                              if_else(non_white_pct >= 0.55 & non_white_pct < 0.60, "55%",
                              if_else(non_white_pct >= 0.60 & non_white_pct < 0.65, "60%",
                              if_else(non_white_pct >= 0.65 & non_white_pct < 0.70, "65%",
                              if_else(non_white_pct >= 0.70 & non_white_pct < 0.75, "70%",
                              if_else(non_white_pct >= 0.75 & non_white_pct < 0.80, "75%",
                              if_else(non_white_pct >= 0.80 & non_white_pct < 0.85, "80%",
                              if_else(non_white_pct >= 0.85 & non_white_pct < 0.90, "85%",
                              if_else(non_white_pct >= 0.90 & non_white_pct < 0.95, "90%",
                              if_else(non_white_pct >= 0.95 & non_white_pct < 1.00, "95%",
                              "100%")))))))))))))))))))))
levels = c("0%","5%", "10%", "15%", "20%", "25%", "30%", "35%", "40%", "45%","50%", "55%", "60%", "65%", "70%","75%","80%","85%","90%","95%","100%")
j40_select$percentile <- factor(j40_select$percentile, levels = levels)
j40_select$definition_m_pctl = as.factor(j40_select$definition_m_pctl)

# Grist Visualization Replication 1 
cols = c("#22a7f0","#e14b31")
ggplot(j40_select, aes(x = percentile, fill = definition_m_pctl))+
  geom_bar(position = "fill")+
  scale_y_continuous(name ="% of Tracts Disadvantaged", labels =  scales::percent)+
  scale_fill_discrete(name = "Census Tract Designation", labels = c("Not Disadvantaged", "Disadvantaged"), type = cols)+
  labs(
      title = "Are more diverse census tracts more likely to be considered disadvanted?",
      x = "Percent of Census Tract that is Non-White",
      caption = "Replication of visualization by Clayton Aldern/The Grist")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 8))


```

```{r}
ggplot(j40_select, aes(x = percentile, fill = definition_m_pctl))+
  geom_bar(aes(weight = summary_est))+
  scale_fill_discrete(name = "Census Tract Designation", labels = c("Not Disadvantaged", "Disadvantaged"), type = cols)+
  scale_y_continuous(labels = scales::comma)+
  labs(
      title = "Population by Disadvantaged Status and Percent Non-White",
      x = "Percent of Census Tract that is Non-White",
      y = "Population")+
  theme_minimal()+
    theme(axis.text.x = element_text(angle = 90),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 8))
```

```{r}
#set color palette 
palette = c("#00203FFF", "#ADEFD1FF")
## mapping DC 
dc = j40_race%>%
  filter(state == "District of Columbia")%>%
  select(GEOID, majority_minority, definition_m_pctl, geometry)%>%
  mutate(both = if_else(majority_minority == 1 & definition_m_pctl == 1, 3,
                if_else(majority_minority == 1 & definition_m_pctl == 0, 2,
                if_else(majority_minority == 0 & definition_m_pctl == 1, 1,
                        0))))
#option 1
ggplot(dc)+
  geom_sf(aes(fill = factor(both)))+
  theme_void()+
  scale_fill_discrete(type = cols, labels = c("Not Disadvantaged/Not Majority-Minority", "Not Disadvantaged/Majority-Minority","Both Disadvantaged and Majority-Minority"))+
  theme(
    legend.title = element_blank()
  )+
  labs(title = "Majority-Minority Tracts and Justice 40")

#option 2
dc_gg1 = ggplot(dc)+
  geom_sf(aes(fill = factor(majority_minority)))+
  scale_fill_discrete(type = cols, labels = c("No", "Yes"))+
  theme_void()+
  labs(title = "Majority-Minority")+
  theme(
    legend.title = element_blank()
  )
dc_gg2 = ggplot(dc)+
  geom_sf(aes(fill = factor(definition_m_pctl)))+
  scale_fill_discrete(type = cols, labels = c("No", "Yes"))+
  theme_void()+
  labs(title = "Justice 40 Disadvantaged")+
  theme(
    legend.title = element_blank()
  )
dc_gg1 + dc_gg2
```

```{r}
### Hennepin County 
hennepin_county = j40_race %>%
  filter(county == "Hennepin County", state == "Minnesota") %>% 
  select(GEOID, majority_minority, definition_m_pctl, geometry)%>%
  mutate(both = if_else(majority_minority == 1 & definition_m_pctl == 1, 3,
                if_else(majority_minority == 1 & definition_m_pctl == 0, 2,
                if_else(majority_minority == 0 & definition_m_pctl == 1, 1,
                        0))))

## plot 1
ggplot(hennepin_county)+
  geom_sf(aes(fill = factor(both)))+
  theme_void()+
  scale_fill_brewer(palette = "Set2", labels = c("Not Disadvantaged/Not Majority-Minority", "Not Disadvantaged/Majority-Minority","Both Disadvantaged and Majority-Minority"))+
  theme(
    legend.title = element_blank()
  )+
  labs(title = "Majority-Minority Tracts and Justice 40")

# comparison
hc_gg1 = ggplot(hennepin_county)+
  geom_sf(aes(fill = factor(majority_minority)))+
  scale_fill_discrete(type = cols, labels = c("No", "Yes"))+
  theme_void()+
  labs(title = "Majority-Minority")+
  theme(
    legend.title = element_blank()
  )
hc_gg2 = ggplot(hennepin_county)+
  geom_sf(aes(fill = factor(definition_m_pctl)))+
  scale_fill_discrete(type = cols, labels = c("No", "Yes"))+
  theme_void()+
  labs(title = "Justice 40 Disadvantaged")+
  theme(
    legend.title = element_blank()
  )
hc_gg1 + hc_gg2
```

```{r}
#community resiliancy
j40_race_fema = j40_race %>%
  left_join(fema_risk, by = c("GEOID" = "TRACTFIPS"))%>%
  mutate(high_risk = if_else(RISK_RATNG == "Relatively High", 1,
                     if_else(RISK_RATNG == "Very High", 1, 0)))

miami_dade = j40_race_fema %>%
  filter(state == "New Mexico")%>%
  select(GEOID, HWAV_RISKR, high_risk, definition_m_pctl, geometry)

#visualization
md_gg1 = ggplot(miami_dade)+
  geom_sf(aes(fill = factor(high_risk)))+
  scale_fill_discrete(type = cols, labels = c("No", "Yes"))+
  theme_void()+
  labs(title = "FEMA High Risk")+
  theme(
    legend.title = element_blank()
  )

md_gg2 = ggplot(miami_dade)+
  geom_sf(aes(fill = factor(definition_m_pctl)))+
  scale_fill_discrete(type = cols, labels = c("No", "Yes"))+
  theme_void()+
  labs(title = "Justice 40 Disadvantaged")+
  theme(
    legend.title = element_blank()
  )
md_gg1 + md_gg2

j40_race %>%
  filter(state == "New Mexico")%>%
  ggplot()+
  geom_sf(aes(fill = factor(definition_m_pctl)))

```

Sand Box Area

```{r}
## missingness analysis
#get fip codes
fips_codes_simple = fips_codes%>%
  select(state_code,state_name) %>%
  distinct()
# where are the missing ACS tracts from
missing_tracts = j40_race %>%
  anti_join(tract_race, by = c("geoid10_tract" = "GEOID"))%>%
  select(geoid10_tract, definition_m_pctl)%>%
  mutate(fip = str_extract(geoid10_tract, "[0-9]{2}"))%>%
  left_join(fips_codes_simple, by = c("fip" = "state_code"))%>% 
  group_by(state_name) %>% 
  summarize(n = n())
missing_tracts
```
